version: 0.2

phases:

  post_build:
    commands:
      - echo Build completed on `date`
      - mvn clean install -Dmaven.test.skip=true
artifacts:
  files:
    - target/SpringBootExample-2.1.2.RELEASE.jar
    - appspec.yml
  discard-paths: yes